name: telegram_clone
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+2
  equatable: ^1.2.5
  rxdart: ^0.24.1
  flutter_bloc: ^6.0.6
  provider: ^4.3.2+2
  url_launcher: ^5.4.2
  intl: ^0.16.1
  cloud_firestore: ^0.16.0+1
  firebase_auth: ^0.20.1
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/profile_photos/
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family:  TelegramIcons
      fonts:
        - asset: fonts/TelegramIcons.ttf
    - family: Gilroy
      fonts:
        - asset: fonts/Radomir_Tinkov-Gilroy-Thin.otf
          weight: 100
        - asset: fonts/Radomir_Tinkov-Gilroy-Regular.otf
        - asset: fonts/Radomir_Tinkov-Gilroy-Medium.otf
          weight: 500
        - asset: fonts/Radomir_Tinkov-Gilroy-SemiBold.otf
          weight: 600
        - asset: fonts/Radomir_Tinkov-Gilroy-Bold.otf
          weight: 700
        - asset: fonts/Radomir_Tinkov-Gilroy-Black.otf
          weight: 800
        - asset: fonts/Radomir_Tinkov-Gilroy-Heavy.otf
          weight: 900
